import { useLocale } from "../../i18n";

export const contentZh = {
  "chat.content.copyFailed": "未能复制，请选中正文手动复制",
  "chat.content.copyCode": "复制代码",
  "chat.content.file": "文件",
  "chat.content.openFile": "打开文件",
  "chat.content.close": "关闭预览",
  "chat.content.download": "下载",
  "chat.content.loading": "正在读取文件…",
  "chat.content.loadFailed": "文件未能打开",
  "chat.content.retry": "重试",
  "chat.content.previewUnavailable": "此格式暂不支持预览，可以下载后打开。",
  "chat.content.contextRequired": "请在原会话中打开这个文件。",
  "chat.content.remoteImage": "加载远程图片",
  "chat.content.remoteImageHint": "加载时会连接图片所在的网站。",
  "chat.content.openLink": "在新窗口打开链接",
  "chat.content.unsupportedLink": "此链接类型暂不支持打开",
  "chat.content.zoomIn": "放大图片",
  "chat.content.zoomOut": "适应窗口",
  "chat.content.source": "源文件",
  "chat.content.preview": "预览",
  "chat.content.htmlRestricted": "预览已禁用脚本、表单和外部资源。",
  "chat.content.tooLarge": "文件较大，暂不在窗口中预览，可以下载后打开。",
  "chat.content.attachment": "附件",
  "chat.content.image": "图片",
  "chat.content.audio": "音频",
  "chat.content.mediaUnavailable": "收到媒体内容，但当前格式无法预览。",
  "chat.content.pdfHint": "若浏览器无法显示 PDF，可以下载后打开。",
  "chat.content.pdfPrevious": "上一页",
  "chat.content.pdfNext": "下一页",
  "chat.content.pdfPage": "页码",
  "chat.content.pdfRendering": "正在绘制页面…",
  "chat.content.pdfFailed": "PDF 未能预览，可以重试或下载后打开。",
  "chat.content.deliveryUnconfirmed": "发送结果未确认",
  "chat.content.deliveryCheckFirst": "请先查看后续消息和任务状态，再决定是否重新发送。",
  "chat.content.checkDelivery": "查看会话状态",
  "chat.content.thumbnailFailed": "缩略图未能加载，点击打开文件",
} as const;

export const contentEn: Record<keyof typeof contentZh, string> = {
  "chat.content.copyFailed": "Could not copy. Select the text and copy it manually.",
  "chat.content.copyCode": "Copy code",
  "chat.content.file": "File",
  "chat.content.openFile": "Open file",
  "chat.content.close": "Close preview",
  "chat.content.download": "Download",
  "chat.content.loading": "Loading file…",
  "chat.content.loadFailed": "Could not open the file",
  "chat.content.retry": "Retry",
  "chat.content.previewUnavailable": "Preview is unavailable for this format. Download it to open it.",
  "chat.content.contextRequired": "Open this file in its original conversation.",
  "chat.content.remoteImage": "Load remote image",
  "chat.content.remoteImageHint": "Loading connects to the website hosting this image.",
  "chat.content.openLink": "Open link in a new window",
  "chat.content.unsupportedLink": "This link type cannot be opened here",
  "chat.content.zoomIn": "Zoom in",
  "chat.content.zoomOut": "Fit to window",
  "chat.content.source": "Source",
  "chat.content.preview": "Preview",
  "chat.content.htmlRestricted": "Scripts, forms, and external resources are disabled in this preview.",
  "chat.content.tooLarge": "This file is too large to preview here. Download it to open it.",
  "chat.content.attachment": "Attachment",
  "chat.content.image": "Image",
  "chat.content.audio": "Audio",
  "chat.content.mediaUnavailable": "Media was received, but this format cannot be previewed.",
  "chat.content.pdfHint": "If your browser cannot display the PDF, download it to open it.",
  "chat.content.pdfPrevious": "Previous page",
  "chat.content.pdfNext": "Next page",
  "chat.content.pdfPage": "Page",
  "chat.content.pdfRendering": "Rendering page…",
  "chat.content.pdfFailed": "Could not preview the PDF. Retry or download it to open it.",
  "chat.content.deliveryUnconfirmed": "Delivery is unconfirmed",
  "chat.content.deliveryCheckFirst": "Check later messages and the task status before deciding to send again.",
  "chat.content.checkDelivery": "Check conversation status",
  "chat.content.thumbnailFailed": "The thumbnail could not load. Click to open the file.",
};

export function useContentText() {
  const { locale, tDynamic } = useLocale();
  return (key: keyof typeof contentZh) => tDynamic(key, (locale === "en" ? contentEn : contentZh)[key]);
}
